apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test
  name: hello-dotnet-app-service
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hello-dotnet-app
  type: NodePort
