resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: mykustomapp

commonAnnotations:
  app: mykustom-annontations

namePrefix: kustom-

configMapGenerator:
  - name: mykustom-map
    env: config.properties
