apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-appnew
  namespace: argocdapp
spec:
  destination:
    server: "https://kubernetes.default.svc" # Your Kubernetes API server URL
    namespace: default
  source:
    repoURL: "https://github.com/SrinathDevOps/MyUsefullinfo.git" # Corrected Git URL format
    targetRevision: main
    path: argocd-manifests # Path to the directory containing your deployment YAML files
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
  syncOptions:
    - validate=true
    - createNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - dryRun=false
    - force=false
    - timeout=0s
    - retry=true
    - retryPeriod=1s
    - retryBackoff=2
    - syncWave=0
    - ApplyOutOfSyncOnly=false
    - SkipDryRunOnMissingResource=false
    - Replace=false
    - SkipHooks=false
    - Validate=false
    - ValidateStrict=false
    - ValidateNonFatal=false
    - ValidateIgnoreUnknownFields=false
