apiVersion: v1
kind: Service
metadata:
  name: hello-dotnet-app-service
spec:
  selector:
    app: hello-dotnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 32362  # Change this to the port used by Argo CD server
  type: LoadBalancer
