name: CD Pipeline Workflow

on:
  workflow_run:
    workflows: [".NET Build Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ./src/HelloWorldApp
      - name: Build Application
        run: dotnet build ./src/HelloWorldApp/HelloWorldapp.sln --configuration Release
        working-directory: ./src/HelloWorldApp
      - name: Publish Application
        run: dotnet publish ./src/HelloWorldApp/HelloWorldapp.sln --configuration Release --output ./publish
        working-directory: ./src/HelloWorldApp
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'your-app-name'  # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./src/HelloWorldApp/publish
