name: CD Pipeline Workflow

on:
  workflow_run:
    workflows: [".NET Build Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Application
        run: dotnet publish ./src/HelloWorldApp/HelloWorldapp.sln --configuration Release --output ./publish
        working-directory: ./src/HelloWorldApp
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "helloapp-dev" # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./src/HelloWorldApp/publish
