name: .NET Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src/HelloWorldApp

      - name: Build
        run: dotnet build ./src/HelloWorldApp/HelloWorldapp.sln --configuration Release

      - name: Publish Application
        run: dotnet publish ./src/HelloWorldApp/HelloWorldapp.sln -c Release --output ./src/HelloWorldApp/myapp
        
      - name: Debug Logs
        run: |
          echo "ACR_USERNAME: $ACR_USERNAME"
          echo "ACR_PASSWORD: $ACR_PASSWORD"

      - name: Build and Push Docker Image
        env:
           ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
           ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: |
          # Log in to Azure Container Registry
          docker login argocdsrips.azurecr.io -u "$ACR_USERNAME" -p "$ACR_PASSWORD"
          
          # Build and push the Docker image
          docker build --file Dockerfile --tag argocdsrips.azurecr.io/hello-dotnet-app:latest.v9 .
          docker push argocdsrips.azurecr.io/hello-dotnet-app:latest.v9

      - name: Update Kubernetes Deployment
        run: |
         echo "Before:"
         cat argocd-manifests/hello-dotnet-app-deployment.yaml
         sed -i 's|image: argocdsrips.azurecr.io/hello-dotnet-app:.*|image: argocdsrips.azurecr.io/hello-dotnet-app:latest.v9|g' argocd-manifests/hello-dotnet-app-deployment.yaml
         sed -i 's|replicas: .*|replicas: 15|g' argocd-manifests/hello-dotnet-app-deployment.yaml
         echo "After:"
         cat argocd-manifests/hello-dotnet-app-deployment.yaml

      - name: Commit Changes
        run: |
          git config --local user.email "srinath.kaithoju@gmail.com"
          git config --local user.name "SrinathDevOps"
          git add .
          git commit -m "Update Kubernetes deployment and replicas"
          git push origin main

      - name: Debug Info
        run: |
         pwd
         ls -R




       
     # - name: Set up Argo CD CLI
     #   run: |
     #    curl -LO https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
      #   chmod +x argocd-linux-amd64
      #   sudo mv argocd-linux-amd64 /usr/local/bin/argocd

    #  - name: Login to Argo CD
     #   run: |
     #    echo "y" | argocd login 172.178.38.39:32362 --insecure --username admin --password 'ElevengthCorner@123' 

     # - name: set permission Argo CD application
       # run: argocd app set hello-dotnet-app --sync-policy automated --self-heal --dest-namespace argocd
     # - name: Sync Argo CD application
      #  run: argocd app sync hello-dotnet-app
     # - name: Sync app creation application
      #  run: argocd app set hello-dotnet-app --sync-policy automated --self-heal --repo https://github.com/SrinathDevOps/MyUsefullinfo.git --path argocd-manifests/apps/hello-dotnet --dest-namespace default --dest-server https://kubernetes.default.svc

  #    - name: Sync app sync
    #    run: argocd app sync hello-dotnet-app

      
   
