name: .NET Build Workflow CID and CD done added code in dev env
on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
env:
  AZURE_WEBAPP_NAME: helloapp-dev
  AZURE_WEBAPP_PACKAGE_PATH: "./src/HelloWorldApp"
  DOTNET_VERSION: "6.0.x"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      # Run dotnet build and publish
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src/HelloWorldApp
      - name: Build
        run: dotnet build ./src/HelloWorldApp/HelloWorldapp.sln --configuration Release
      - name: Publish Application
        run: dotnet publish ./src/HelloWorldApp/HelloWorldapp.sln -c Release --output ./src/HelloWorldApp/myapp
      - name: Deploy to Dev
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: helloapp-dev
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "./src/HelloWorldApp/myapp"
      - name: helloworldsrips-uat
        if: github.ref == 'refs/heads/release/2023.10.100'
        uses: azure/webapps-deploy@v2
        with:
          app-name: helloapp-uat
          publish-profile: ${{ secrets.AZURE_WEBAPP_UAT_PUBLISH_PROFILE }}
          package: "./src/HelloWorldApp/myapp"

      - name: Deploy to Prod
        if: startsWith(github.ref, 'refs/tags/')
        uses: azure/webapps-deploy@v2
        with:
          app-name: helloworldsrips
          publish-profile: ${{ secrets.AZURE_WEBAPP_PROD_PUBLISH_PROFILE }}
          package: "./src/HelloWorldApp/myapp"
